from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from video_channel_manager.platforms.vk.milovi_immediate_wall import MILOVI_COMMUNITY_ID, MILOVI_OWNER_ID
from video_channel_manager.platforms.vk.milovi_rollout_sources import write_json_atomic
from video_channel_manager.platforms.vk.milovi_token_clip_rollout import MiloviTokenRolloutBlocked

ANOMALY_SOURCE_ID = "o1WXIMupuws"
ANOMALY_CLIP_REMOTE_ID = "-68859909_456239232"
ANOMALY_POST_ID = 475
ANOMALY_WALL_REMOTE_ID = f"{MILOVI_OWNER_ID}_{ANOMALY_POST_ID}"
ANOMALY_STATE_SCHEMA = "video-manager.milovi-issue-323-anomaly-cleanup-state"
LEGACY_FINALIZER_SCHEMA = "video-manager.milovi-issue-323-finalizer"
LEGACY_MARKER_PREFIX = "youtube.com/shorts/"


class MiloviIssue323AnomalyBlocked(MiloviTokenRolloutBlocked):
    """The exact wall-475 anomaly cleanup cannot be proved safe."""


def _identity_binding() -> dict[str, object]:
    return {
        "community_id": MILOVI_COMMUNITY_ID,
        "owner_id": MILOVI_OWNER_ID,
        "anomaly_wall_remote_id": ANOMALY_WALL_REMOTE_ID,
        "anomaly_clip_remote_id": ANOMALY_CLIP_REMOTE_ID,
    }


def _new_anomaly_state() -> dict[str, Any]:
    return {
        "schema_name": ANOMALY_STATE_SCHEMA,
        "schema_version": 1,
        **_identity_binding(),
        "cleanup_475": {"status": "uninitialized_no_delete_authority", "delete_authority": False},
    }


def _validate_identity(payload: Mapping[str, Any]) -> None:
    mismatch = {
        key: {"expected": value, "actual": payload.get(key)}
        for key, value in _identity_binding().items()
        if payload.get(key) != value
    }
    if mismatch:
        raise MiloviIssue323AnomalyBlocked(f"Anomaly cleanup state binding mismatch: {mismatch}")
    if not isinstance(payload.get("cleanup_475"), dict):
        raise MiloviIssue323AnomalyBlocked("Anomaly cleanup state has no cleanup_475 object")


def load_anomaly_cleanup_state(path: Path) -> dict[str, Any]:
    """Load only wall-475 durable state, including a legacy finalizer journal.

    A legacy journal remains valid evidence for cleanup_475, but its generated
    promotion_plan and edit maps are deliberately not validated or consulted.
    That prevents autogenerated promotion copy from remaining an implicit
    source of truth after the promotion finalizer is retired.
    """

    if not path.is_file():
        payload = _new_anomaly_state()
        write_json_atomic(path, payload)
        return payload
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise MiloviIssue323AnomalyBlocked("Anomaly cleanup state is not a JSON object")
    schema_name = payload.get("schema_name")
    if schema_name not in {ANOMALY_STATE_SCHEMA, LEGACY_FINALIZER_SCHEMA}:
        raise MiloviIssue323AnomalyBlocked(f"Unsupported anomaly cleanup state schema: {schema_name!r}")
    if payload.get("schema_version") != 1:
        raise MiloviIssue323AnomalyBlocked("Unsupported anomaly cleanup state schema version")
    _validate_identity(payload)
    return payload


def save_anomaly_cleanup_state(path: Path, state: dict[str, Any]) -> None:
    """Persist the exact document that was loaded, preserving legacy evidence."""

    _validate_identity(state)
    write_json_atomic(path, state)


def legacy_source_marker_ok(item: Mapping[str, Any], source_id: str) -> bool:
    marker = f"{LEGACY_MARKER_PREFIX}{source_id}".casefold()
    return marker in str(item.get("description") or "").casefold()


__all__ = [
    "ANOMALY_CLIP_REMOTE_ID",
    "ANOMALY_POST_ID",
    "ANOMALY_SOURCE_ID",
    "ANOMALY_STATE_SCHEMA",
    "ANOMALY_WALL_REMOTE_ID",
    "MiloviIssue323AnomalyBlocked",
    "legacy_source_marker_ok",
    "load_anomaly_cleanup_state",
    "save_anomaly_cleanup_state",
]
