"""Guarded @lordchrist Telegram publication facade.

The public API stays in one repository-owned module while the implementation is
split into immutable models, strict state transitions, and provider transport.
"""

from video_channel_manager.telegram_models import (
    CHANNEL_USERNAME,
    DEFAULT_API_BASE,
    MAX_TELEGRAM_TEXT_LENGTH,
    PRIMARY_SOURCE_HOSTS,
    PROJECT_KEY,
    PUBLICATION_TIMEZONE,
    DispatchEnvelope,
    DispatchMode,
    LedgerEntry,
    PreparedDispatch,
    ProviderEffect,
    SourceProof,
    StateName,
    TargetProof,
    TelegramLedger,
    TelegramPost,
    TelegramQueue,
)
from video_channel_manager.telegram_state import (
    initialize_ledger,
    initialize_ledger_file,
    load_dispatch,
    load_ledger,
    load_or_initialize_ledger,
    load_queue,
    load_target_proof,
    prepare_next,
    preview_next,
    publication_local_date,
    require_execution_enabled,
    require_preflight_config,
    resolve_entry,
    save_ledger,
    save_model,
    strict_next_post,
    utc_now,
    verify_dispatch_against_queue,
    verify_persisted_intent,
)
from video_channel_manager.telegram_transport import TelegramApiError, dispatch_prepared, preflight_target

__all__ = [
    "CHANNEL_USERNAME",
    "DEFAULT_API_BASE",
    "MAX_TELEGRAM_TEXT_LENGTH",
    "PRIMARY_SOURCE_HOSTS",
    "PROJECT_KEY",
    "PUBLICATION_TIMEZONE",
    "DispatchEnvelope",
    "DispatchMode",
    "LedgerEntry",
    "PreparedDispatch",
    "ProviderEffect",
    "SourceProof",
    "StateName",
    "TargetProof",
    "TelegramApiError",
    "TelegramLedger",
    "TelegramPost",
    "TelegramQueue",
    "dispatch_prepared",
    "initialize_ledger",
    "initialize_ledger_file",
    "load_dispatch",
    "load_ledger",
    "load_or_initialize_ledger",
    "load_queue",
    "load_target_proof",
    "preflight_target",
    "prepare_next",
    "preview_next",
    "publication_local_date",
    "require_execution_enabled",
    "require_preflight_config",
    "resolve_entry",
    "save_ledger",
    "save_model",
    "strict_next_post",
    "utc_now",
    "verify_dispatch_against_queue",
    "verify_persisted_intent",
]
